// <auto-generated />
using System;
using HonStats.Infra.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HonStats.Infra.Migrations
{
    [DbContext(typeof(HonStatsDbContext))]
    [Migration("20260703094901_CaptureMatchMetrics")]
    partial class CaptureMatchMetrics
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("HonStats.Domain.Insights.HeroBuild", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Frequency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Games")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Wins")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "HeroId", "ItemId");

                    b.HasIndex("AccountId", "HeroId");

                    b.ToTable("hero_builds", (string)null);
                });

            modelBuilder.Entity("HonStats.Domain.Insights.IndexedPlayer", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("IndexedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LastIndexedMatchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastReindexAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("indexed_players", (string)null);
                });

            modelBuilder.Entity("HonStats.Domain.Insights.MatchItemTiming", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("FirstSeenSeconds")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "AccountId", "ItemId");

                    b.HasIndex("AccountId", "ItemId");

                    b.ToTable("match_item_timing", (string)null);
                });

            modelBuilder.Entity("HonStats.Domain.Insights.MatchPlayerItem", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Slot")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ItemId")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "AccountId", "Slot");

                    b.ToTable("match_player_items", (string)null);
                });

            modelBuilder.Entity("HonStats.Domain.Insights.MatchRoster", b =>
                {
                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("BuildingDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Buybacks")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreepDenies")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("CreepKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("DeathGoldLost")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Experience")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldFromAssists")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldFromBuildings")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldFromCreeps")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldFromKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("GoldFromNeutrals")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroDamage")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Level")
                        .HasColumnType("REAL");

                    b.Property<int?>("NetWorth")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("NeutralKills")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RavenPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoleIndex")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("StartingGold")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("WardOfRevelationPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("WardOfSightPlaced")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Won")
                        .HasColumnType("INTEGER");

                    b.HasKey("GameId", "AccountId");

                    b.HasIndex("AccountId");

                    b.HasIndex("AccountId", "HeroId");

                    b.ToTable("match_roster", (string)null);
                });

            modelBuilder.Entity("HonStats.Domain.Insights.MmrSnapshot", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("CapturedDate")
                        .HasColumnType("TEXT");

                    b.Property<double>("CurrentMmr")
                        .HasColumnType("REAL");

                    b.Property<double>("RankedCaldavarRating")
                        .HasColumnType("REAL");

                    b.Property<double>("RankedMidwarsRating")
                        .HasColumnType("REAL");

                    b.HasKey("AccountId", "CapturedDate");

                    b.HasIndex("AccountId");

                    b.ToTable("mmr_snapshots", (string)null);
                });

            modelBuilder.Entity("HonStats.Domain.Insights.Teammate", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TeammateAccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GamesTogether")
                        .HasColumnType("INTEGER");

                    b.Property<int>("WinsTogether")
                        .HasColumnType("INTEGER");

                    b.HasKey("AccountId", "TeammateAccountId");

                    b.HasIndex("AccountId");

                    b.ToTable("teammates", (string)null);
                });

            modelBuilder.Entity("HonStats.Domain.Matches.PlayerMatch", b =>
                {
                    b.Property<Guid>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("GameId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Assists")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("Deaths")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Duration")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HeroId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsArranged")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Kills")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Map")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Team")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("WinningTeam")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId", "GameId");

                    b.HasIndex("AccountId");

                    b.ToTable("player_matches", (string)null);
                });

            modelBuilder.Entity("HonStats.Domain.Players.Player", b =>
                {
                    b.Property<Guid>("AccountId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Country")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.HasIndex("Username");

                    b.ToTable("players", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
